FROM openjdk:8
WORKDIR /usrapp/bin

ENV PORT 2703
ENV URL1 ""
ENV URL2 ""

COPY /target/classes /usrapp/bin/classes
COPY /target/dependency  /usrapp/bin/dependency

CMD ["java", "-cp", "./classes:./dependency/*", "edu.escuelaing.arep.ProxyServer"]